name: PeeVeePeeArena
main: no.runsafe.peeveepeearena.Plugin
version: 1.0.@BUILD@
author: Kruithne
description:
commands:
  createchestdrop:
    description: Creates a loot table for the chest drop
  forcepvpchest:
    description: Forces a PvP chest in the arena.
